{% set version = "3.36" %}

package:
  name: synda
  version: {{ version }}

source:
  path: ../.

build:
  number: 1
  noarch: generic

channels:
  - conda-forge

dependencies:
- python>=3.8
- pip
- pip:
  # works for regular pip packages
  - asyncio
  - python3-wget

requirements:
  host:
    - python
    - numpy
  run:
    - python
    - six
    - python-daemon
    - psutil
    - retrying
    - progress
    - tabulate
    - humanize
    - beautifulsoup4
    - babel
    - reportlab
    - requests
    - MyProxyClient
    - pycountry
    - texttable
    - pytest
    - pytest-asyncio
    - pandas
    - aiohttp
    - aiofiles
    - httpx

about:
    home: https://github.com/Prodiguer/synda
    license: Public
    summary: 'Synda data transfer module'
    description: This program download files from the Earth System Grid Federation (ESGF) archive using command line.
    dev_url: https://github.com/Prodiguer/synda
    doc_url: http://prodiguer.github.io/synda/
    doc_source_url: https://github.com/Prodiguer/synda/blob/master/README.md
