{% set version = "3.4" %}

package:
  name: synda
  version: {{ version }}

source:
  path: ../.

build:
  number: 2
  noarch: python

channels:
  - conda-forge

dependencies:
  - python>=3.9
  - pip
  - pip:
    # works for regular pip packages
    - asyncio
    - uvloop

requirements:
  build:
    - openssl=1.1.1l
    - cryptography=36.0.1
    - numpy=1.16
  host:
    - python
    - numpy
  run:
    - numpy
    - python
    - six
    - psutil
    - retrying
    - progress
    - tabulate
    - humanize
    - beautifulsoup4
    - babel
    - reportlab
    - requests
    - MyProxyClient
    - pycountry
    - texttable
    - pytest
    - pytest-asyncio
    - pandas
    - aiohttp
    - aiofiles
    - uvloop
    - cryptography
    - openssl

about:
    home: https://github.com/Prodiguer/synda
    license: Public
    summary: 'Synda data transfer module'
    description: This program download files from the Earth System Grid Federation (ESGF) archive using command line.
    dev_url: https://github.com/Prodiguer/synda
    doc_url: http://prodiguer.github.io/synda/
    doc_source_url: https://github.com/Prodiguer/synda/blob/master/README.md
