{% set version = "3.11" %}

package:
  name: synda
  version: {{ version }}

source:
  path: ../.

build:
  number: 10
  noarch: generic
  entry_points:
    - synda = synda:run

requirements:
  host:
    - python
  run:
    - python
    - six
    - python-daemon
    - psutil
    - retrying
    - progress
    - tabulate
    - humanize
    - beautifulsoup4
    - babel
    - reportlab
    - requests
    - 'MyProxyClient[channel=ipsl]'
    - 'pycountry[channel=ipsl]'
    - 'globusonline-transfer-api-client[channel=ipsl]'
    - 'texttable[channel=ipsl]'
    - 'python-jsonrpc[channel=ipsl]'
about:
    home: https://github.com/Prodiguer/synda
    license: Public
    summary: 'Synda data transfer module'
    description: This program download files from the Earth System Grid Federation (ESGF) archive using command line.
    dev_url: https://github.com/Prodiguer/synda
    doc_url: http://prodiguer.github.io/synda/
    doc_source_url: https://github.com/Prodiguer/synda/blob/master/README.md
